/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.rrobot.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;


/**
 * Use this class to register components to be used within the IDE.
 */
public class RTaskUiModule extends org.eclipse.fx.ide.rrobot.dsl.ui.AbstractRTaskUiModule {
	public RTaskUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
