/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.gmodel.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGModelDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.eclipse.fx.ide.gmodel.gModelDSL.GModelDSLPackage.eINSTANCE);
		return result;
	}
}
