/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.gmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GModelDSLUiModule extends org.eclipse.fx.ide.gmodel.ui.AbstractGModelDSLUiModule {
	public GModelDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
