/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.gmodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GModelDSLRuntimeModule extends org.eclipse.fx.ide.gmodel.AbstractGModelDSLRuntimeModule {

}
