/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.gmodel;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GModelDSLStandaloneSetup extends GModelDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new GModelDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

