/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.gmodel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.fx.ide.gmodel.services.GModelDSLGrammarAccess;

public class GModelDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GModelDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.fx.ide.gmodel.parser.antlr.internal.InternalGModelDSLParser createParser(XtextTokenStream stream) {
		return new org.eclipse.fx.ide.gmodel.parser.antlr.internal.InternalGModelDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "GModel";
	}
	
	public GModelDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GModelDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
