/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.fxgraph.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FXGraphAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/fx/ide/fxgraph/parser/antlr/internal/InternalFXGraph.tokens");
	}
}
