/*
* generated by Xtext
*/
package org.eclipse.fx.ide.rrobot.dsl.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RTaskProposalProvider extends AbstractRTaskProposalProvider {

}
