/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.l10n.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.fx.ide.l10n.ui.internal.NLSDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NLSDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return NLSDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return NLSDslActivator.getInstance().getInjector(NLSDslActivator.ORG_ECLIPSE_FX_IDE_L10N_NLSDSL);
	}
	
}
