/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.css.cssext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CssExtDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/fx/ide/css/cssext/parser/antlr/internal/InternalCssExtDsl.tokens");
	}
}
