/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.l10n;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NLSDslRuntimeModule extends org.eclipse.fx.ide.l10n.AbstractNLSDslRuntimeModule {

}
