/*
* generated by Xtext
*/
package org.eclipse.fx.ide.l10n;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class NLSDslStandaloneSetup extends NLSDslStandaloneSetupGenerated{

	public static void doSetup() {
		new NLSDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

