<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="anttasks" nsURI="http://org.eclipse.fx.ide.jdt/1.0" nsPrefix="anttasks">
  <eClassifiers xsi:type="ecore:EClass" name="AntTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploy" eType="#//Deploy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jar" eType="#//Jar" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signjar" eType="#//SignJar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildDirectory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manifestEntries" upperBound="-1"
        eType="#//parameters/Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cssToBin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//parameters/KeyValuePair" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonts" upperBound="-1"
        eType="#//parameters/KeyValuePair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deploy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="embedjnlp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeDT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offlineAllowed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholderref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholderid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatemode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="background"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" eType="#//parameters/Platform"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferences" eType="#//parameters/Preferences"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//parameters/Application"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" eType="#//parameters/Permissions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//parameters/Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callbacks" upperBound="-1"
        eType="#//parameters/Callback" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="info" eType="#//parameters/Info"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splashImage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packagingFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verbose" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proxyResolution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="android" eType="#//android/AndroidExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Jar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" eType="#//parameters/Platform"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileset" eType="#//parameters/FileSet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//parameters/Application"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="info" eType="#//parameters/Info"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignJar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keypass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keystore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storepass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storetype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PackagingFormat">
    <eLiterals name="none" literal="none"/>
    <eLiterals name="all" value="1" literal="all"/>
    <eLiterals name="image" value="2" literal="image"/>
    <eLiterals name="exe" value="3" literal="exe"/>
    <eLiterals name="msi" value="4" literal="msi"/>
    <eLiterals name="dmg" value="5" literal="dmg"/>
    <eLiterals name="rpm" value="6" literal="rpm"/>
    <eLiterals name="deb" value="7" literal="deb"/>
  </eClassifiers>
  <eSubpackages name="parameters" nsURI="http://org.eclipse.fx.ide.jdt/parameters/1.0"
      nsPrefix="parameters">
    <eClassifiers xsi:type="ecore:EClass" name="FileSet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="includes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredfor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//parameters/FileSetType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FileSetType">
      <eLiterals name="auto" literal="auto"/>
      <eLiterals name="jar" value="1" literal="jar"/>
      <eLiterals name="jnlp" value="2" literal="jnlp"/>
      <eLiterals name="native" value="3" literal="native"/>
      <eLiterals name="icon" value="4" literal="icon"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Platform">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="refid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="javafx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="2.1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="j2se" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jVmArgs" upperBound="-1"
          eType="#//parameters/JVmArg" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//parameters/Property" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JVmArg">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Preferences">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="install" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="menu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="refid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortcut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Application">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallbackclass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainclass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="preloaderclass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="refid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="toolkit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//parameters/Argument" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="htmlParams" upperBound="-1"
          eType="#//parameters/HtmlParam" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
          eType="#//parameters/Param" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Argument"/>
    <eClassifiers xsi:type="ecore:EClass" name="HtmlParam">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="escape" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Param">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Permissions">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cachecertificates" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elevated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Template">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="toFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Callback">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="refid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="callbacks" upperBound="-1"
          eType="#//parameters/Callback" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Info">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="vendor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="icon" upperBound="-1"
          eType="#//parameters/Icon" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="splash" upperBound="-1"
          eType="#//parameters/Splash" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Icon">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="href" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//parameters/IconType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="IconType">
      <eLiterals name="default" literal="default"/>
      <eLiterals name="disabled" value="1" literal="disabled"/>
      <eLiterals name="rollover" value="2" literal="rollover"/>
      <eLiterals name="selected" value="3" literal="selected"/>
      <eLiterals name="shortcut" value="4" literal="shortcut"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Splash">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="href" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//parameters/SplashMode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SplashMode">
      <eLiterals name="any" literal="any"/>
      <eLiterals name="webstart" literal="webstart"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KeyValuePair">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ApplicationToolkitType">
      <eLiterals name="fx" literal="fx"/>
      <eLiterals name="swing" value="1" literal="swing"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="android" nsURI="http://org.eclipse.fx.ide.jdt/1.0/android" nsPrefix="android">
    <eClassifiers xsi:type="ecore:EClass" name="AndroidExport">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="androidsdk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dalviksdk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="activityLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persmissionList" upperBound="-1"
          eType="#//android/Permission"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Permission">
      <eLiterals name="ACCESS_CHECKIN_PROPERTIES"/>
      <eLiterals name="ACCESS_COARSE_LOCATION" value="1"/>
      <eLiterals name="ACCESS_FINE_LOCATION" value="2"/>
      <eLiterals name="ACCESS_LOCATION_EXTRA_COMMANDS" value="3"/>
      <eLiterals name="ACCESS_MOCK_LOCATION" value="4"/>
      <eLiterals name="ACCESS_NETWORK_STATE" value="5"/>
      <eLiterals name="ACCESS_SURFACE_FLINGER" value="6"/>
      <eLiterals name="ACCESS_WIFI_STATE" value="7"/>
      <eLiterals name="ACCOUNT_MANAGER" value="8"/>
      <eLiterals name="ADD_VOICEMAIL" value="9"/>
      <eLiterals name="AUTHENTICATE_ACCOUNTS" value="10"/>
      <eLiterals name="BATTERY_STATS" value="11"/>
      <eLiterals name="BIND_ACCESSIBILITY_SERVICE" value="12"/>
      <eLiterals name="BIND_APPWIDGET" value="13"/>
      <eLiterals name="BIND_DEVICE_ADMIN" value="14"/>
      <eLiterals name="BIND_DREAM_SERVICE" value="15"/>
      <eLiterals name="BIND_INPUT_METHOD" value="16"/>
      <eLiterals name="BIND_NFC_SERVICE" value="17"/>
      <eLiterals name="BIND_NOTIFICATION_LISTENER_SERVICE" value="18"/>
      <eLiterals name="BIND_PRINT_SERVICE" value="19"/>
      <eLiterals name="BIND_REMOTEVIEWS" value="20"/>
      <eLiterals name="BIND_TEXT_SERVICE" value="21"/>
      <eLiterals name="BIND_TV_INPUT" value="22"/>
      <eLiterals name="BIND_VOICE_INTERACTION" value="23"/>
      <eLiterals name="BIND_VPN_SERVICE" value="24"/>
      <eLiterals name="BIND_WALLPAPER" value="25"/>
      <eLiterals name="BLUETOOTH" value="26"/>
      <eLiterals name="BLUETOOTH_ADMIN" value="27"/>
      <eLiterals name="BLUETOOTH_PRIVILEGED" value="28"/>
      <eLiterals name="BODY_SENSORS" value="29"/>
      <eLiterals name="BRICK" value="30"/>
      <eLiterals name="BROADCAST_PACKAGE_REMOVED" value="31"/>
      <eLiterals name="BROADCAST_SMS" value="32"/>
      <eLiterals name="BROADCAST_STICKY" value="33"/>
      <eLiterals name="BROADCAST_WAP_PUSH" value="34"/>
      <eLiterals name="CALL_PHONE" value="35"/>
      <eLiterals name="CALL_PRIVILEGED" value="36"/>
      <eLiterals name="CAMERA" value="37"/>
      <eLiterals name="CAPTURE_AUDIO_OUTPUT" value="38"/>
      <eLiterals name="CAPTURE_SECURE_VIDEO_OUTPUT" value="39"/>
      <eLiterals name="CAPTURE_VIDEO_OUTPUT" value="40"/>
      <eLiterals name="CHANGE_COMPONENT_ENABLED_STATE" value="41"/>
      <eLiterals name="CHANGE_CONFIGURATION" value="42"/>
      <eLiterals name="CHANGE_NETWORK_STATE" value="43"/>
      <eLiterals name="CHANGE_WIFI_MULTICAST_STATE" value="44"/>
      <eLiterals name="CHANGE_WIFI_STATE" value="45"/>
      <eLiterals name="CLEAR_APP_CACHE" value="46"/>
      <eLiterals name="CLEAR_APP_USER_DATA" value="47"/>
      <eLiterals name="CONTROL_LOCATION_UPDATES" value="48"/>
      <eLiterals name="DELETE_CACHE_FILES" value="49"/>
      <eLiterals name="DELETE_PACKAGES" value="50"/>
      <eLiterals name="DEVICE_POWER" value="51"/>
      <eLiterals name="DIAGNOSTIC" value="52"/>
      <eLiterals name="DISABLE_KEYGUARD" value="53"/>
      <eLiterals name="DUMP" value="54"/>
      <eLiterals name="EXPAND_STATUS_BAR" value="55"/>
      <eLiterals name="FACTORY_TEST" value="56"/>
      <eLiterals name="FLASHLIGHT" value="57"/>
      <eLiterals name="FORCE_BACK" value="58"/>
      <eLiterals name="GET_ACCOUNTS" value="59"/>
      <eLiterals name="GET_PACKAGE_SIZE" value="60"/>
      <eLiterals name="GET_TASKS" value="61"/>
      <eLiterals name="GET_TOP_ACTIVITY_INFO" value="62"/>
      <eLiterals name="GLOBAL_SEARCH" value="63"/>
      <eLiterals name="HARDWARE_TEST" value="64"/>
      <eLiterals name="INJECT_EVENTS" value="65"/>
      <eLiterals name="INSTALL_LOCATION_PROVIDER" value="66"/>
      <eLiterals name="INSTALL_PACKAGES" value="67"/>
      <eLiterals name="INSTALL_SHORTCUT" value="68"/>
      <eLiterals name="INTERNAL_SYSTEM_WINDOW" value="69"/>
      <eLiterals name="INTERNET" value="70"/>
      <eLiterals name="KILL_BACKGROUND_PROCESSES" value="71"/>
      <eLiterals name="LOCATION_HARDWARE" value="72"/>
      <eLiterals name="MANAGE_ACCOUNTS" value="73"/>
      <eLiterals name="MANAGE_APP_TOKENS" value="74"/>
      <eLiterals name="MANAGE_DOCUMENTS" value="75"/>
      <eLiterals name="MASTER_CLEAR" value="76"/>
      <eLiterals name="MEDIA_CONTENT_CONTROL" value="77"/>
      <eLiterals name="MODIFY_AUDIO_SETTINGS" value="78"/>
      <eLiterals name="MODIFY_PHONE_STATE" value="79"/>
      <eLiterals name="MOUNT_FORMAT_FILESYSTEMS" value="80"/>
      <eLiterals name="MOUNT_UNMOUNT_FILESYSTEMS" value="81"/>
      <eLiterals name="NFC" value="82"/>
      <eLiterals name="PERSISTENT_ACTIVITY" value="83"/>
      <eLiterals name="PROCESS_OUTGOING_CALLS" value="84"/>
      <eLiterals name="READ_CALENDAR" value="85"/>
      <eLiterals name="READ_CALL_LOG" value="86"/>
      <eLiterals name="READ_CONTACTS" value="87"/>
      <eLiterals name="READ_EXTERNAL_STORAGE" value="88"/>
      <eLiterals name="READ_FRAME_BUFFER" value="89"/>
      <eLiterals name="READ_HISTORY_BOOKMARKS" value="90"/>
      <eLiterals name="READ_INPUT_STATE" value="91"/>
      <eLiterals name="READ_LOGS" value="92"/>
      <eLiterals name="READ_PHONE_STATE" value="93"/>
      <eLiterals name="READ_PROFILE" value="94"/>
      <eLiterals name="READ_SMS" value="95"/>
      <eLiterals name="READ_SOCIAL_STREAM" value="96"/>
      <eLiterals name="READ_SYNC_SETTINGS" value="97"/>
      <eLiterals name="READ_SYNC_STATS" value="98"/>
      <eLiterals name="READ_USER_DICTIONARY" value="99"/>
      <eLiterals name="READ_VOICEMAIL" value="100"/>
      <eLiterals name="REBOOT" value="101"/>
      <eLiterals name="RECEIVE_BOOT_COMPLETED" value="102"/>
      <eLiterals name="RECEIVE_MMS" value="103"/>
      <eLiterals name="RECEIVE_SMS" value="104"/>
      <eLiterals name="RECEIVE_WAP_PUSH" value="105"/>
      <eLiterals name="RECORD_AUDIO" value="106"/>
      <eLiterals name="REORDER_TASKS" value="107"/>
      <eLiterals name="RESTART_PACKAGES" value="108"/>
      <eLiterals name="SEND_RESPOND_VIA_MESSAGE" value="109"/>
      <eLiterals name="SEND_SMS" value="110"/>
      <eLiterals name="SET_ACTIVITY_WATCHER" value="111"/>
      <eLiterals name="SET_ALARM" value="112"/>
      <eLiterals name="SET_ALWAYS_FINISH" value="113"/>
      <eLiterals name="SET_ANIMATION_SCALE" value="114"/>
      <eLiterals name="SET_DEBUG_APP" value="115"/>
      <eLiterals name="SET_ORIENTATION" value="116"/>
      <eLiterals name="SET_POINTER_SPEED" value="117"/>
      <eLiterals name="SET_PREFERRED_APPLICATIONS" value="118"/>
      <eLiterals name="SET_PROCESS_LIMIT" value="119"/>
      <eLiterals name="SET_TIME" value="120"/>
      <eLiterals name="SET_TIME_ZONE" value="121"/>
      <eLiterals name="SET_WALLPAPER" value="122"/>
      <eLiterals name="SET_WALLPAPER_HINTS" value="123"/>
      <eLiterals name="SIGNAL_PERSISTENT_PROCESSES" value="124"/>
      <eLiterals name="STATUS_BAR" value="125"/>
      <eLiterals name="SUBSCRIBED_FEEDS_READ" value="126"/>
      <eLiterals name="SUBSCRIBED_FEEDS_WRITE" value="127"/>
      <eLiterals name="SYSTEM_ALERT_WINDOW" value="128"/>
      <eLiterals name="TRANSMIT_IR" value="129"/>
      <eLiterals name="UNINSTALL_SHORTCUT" value="130"/>
      <eLiterals name="UPDATE_DEVICE_STATS" value="131"/>
      <eLiterals name="USE_CREDENTIALS" value="132"/>
      <eLiterals name="USE_SIP" value="133"/>
      <eLiterals name="VIBRATE" value="134"/>
      <eLiterals name="WAKE_LOCK" value="135"/>
      <eLiterals name="WRITE_APN_SETTINGS" value="136"/>
      <eLiterals name="WRITE_CALENDAR" value="137"/>
      <eLiterals name="WRITE_CALL_LOG" value="138"/>
      <eLiterals name="WRITE_CONTACTS" value="139"/>
      <eLiterals name="WRITE_EXTERNAL_STORAGE" value="140"/>
      <eLiterals name="WRITE_GSERVICES" value="141"/>
      <eLiterals name="WRITE_HISTORY_BOOKMARKS" value="142"/>
      <eLiterals name="WRITE_PROFILE" value="143"/>
      <eLiterals name="WRITE_SECURE_SETTINGS" value="144"/>
      <eLiterals name="WRITE_SETTINGS" value="145"/>
      <eLiterals name="WRITE_SMS" value="146"/>
      <eLiterals name="WRITE_SOCIAL_STREAM" value="147"/>
      <eLiterals name="WRITE_SYNC_SETTINGS" value="148"/>
      <eLiterals name="WRITE_USER_DICTIONARY" value="149"/>
      <eLiterals name="WRITE_VOICEMAIL" value="150"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
