/*
 * generated by Xtext
 */
package org.eclipse.fx.ide.rrobot.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.fx.ide.rrobot.dsl.ui.internal.RTaskActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RTaskExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RTaskActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RTaskActivator.getInstance().getInjector(RTaskActivator.ORG_ECLIPSE_FX_IDE_RROBOT_DSL_RTASK);
	}
	
}
